#!/usr/bin/env python3
"""
Data Quality Analysis Script

Analyzes flags generated by apply_analytics.py and provides comprehensive
data quality reports, filtering, and export capabilities.

Flags created in: normalize_all_metrics() function in apply_analytics.py (lines 106-171)

Usage:
    python3 analyze_data_quality.py --data-dir ./data
    python3 analyze_data_quality.py --data-dir ./data --report
    python3 analyze_data_quality.py --data-dir ./data --export-flagged flagged_data.csv
    python3 analyze_data_quality.py --data-dir ./data --focus x4_spike
"""

import argparse
from pathlib import Path
from typing import Optional, Sequence

import pandas as pd
import numpy as np


def load_merged(data_dir: Path) -> pd.DataFrame:
    """Load merged_filtered.csv with all normalized metrics and flags."""
    candidates = [
        data_dir / "data" / "filtered" / "merged_filtered.csv",
        data_dir / "filtered" / "merged_filtered.csv",
        data_dir / "merged_filtered.csv",
    ]
    for p in candidates:
        if p.exists():
            return pd.read_csv(p)
    raise FileNotFoundError("merged_filtered.csv not found")


def analyze_all_flags(df: pd.DataFrame) -> None:
    """Generate comprehensive report on all data quality flags."""

    print("\n" + "=" * 120)
    print("DATA QUALITY FLAGS - COMPREHENSIVE ANALYSIS")
    print("=" * 120)

    # Overall statistics
    total_rows = len(df)
    flagged_rows = (df["flag_data_quality_issues"] > 0).sum()
    clean_rows = total_rows - flagged_rows

    print(f"\n📊 OVERALL STATISTICS:")
    print(f"  Total rows: {total_rows:,}")
    print(f"  Clean rows (no flags): {clean_rows:,} ({clean_rows/total_rows*100:.1f}%)")
    print(f"  Flagged rows (1+ issues): {flagged_rows:,} ({flagged_rows/total_rows*100:.1f}%)")

    # Individual flag breakdown
    print(f"\n🚩 INDIVIDUAL FLAG BREAKDOWN:")

    flags = {
        "flag_x1_extreme": ("Working Capital Anomaly", "abs(X1) > 2.0"),
        "flag_x2_extreme": ("Extreme Profitability Loss", "X2 < -0.5 (loss > 50% assets)"),
        "flag_x3_extreme": ("Extreme EBIT Loss", "X3 < -0.3 (operating loss > 30% assets)"),
        "flag_x4_spike": ("Market Valuation Spike", "X4 > company-specific cap"),
        "flag_x4_consistently_high": ("Consistently High Valuation", "Median X4 > 50x"),
        "flag_x5_negative": ("❌ DATA ERROR: Negative Revenue", "X5 < 0 (impossible!)"),
        "flag_leverage_extreme": ("❌ INSOLVENT: TL > TA", "Leverage > 1.0 (liabilities > assets)"),
    }

    for col, (description, trigger) in flags.items():
        count = df[col].sum()
        pct = count / total_rows * 100
        status = "✓" if count == 0 else "⚠️" if count < 100 else "🔴"
        print(f"\n  {status} {description}")
        print(f"     Trigger: {trigger}")
        print(f"     Count: {count:,} rows ({pct:.1f}%)")

    # Multi-flag analysis
    print(f"\n📈 MULTIPLE FLAGS PER ROW:")
    multi_flag_dist = df["flag_data_quality_issues"].value_counts().sort_index()
    for num_flags, count in multi_flag_dist.items():
        if num_flags > 0:
            print(f"  Rows with {num_flags} flag(s): {count:,} ({count/total_rows*100:.1f}%)")

    # Z-score comparison by flag status
    print(f"\n📊 Z-SCORE COMPARISON:")
    print(f"  Clean data (no flags):")
    clean_z = df[df["flag_data_quality_issues"] == 0]["AltmanZScore_Normalized"]
    print(f"    Mean: {clean_z.mean():.2f}")
    print(f"    Median: {clean_z.median():.2f}")
    print(f"    Safe (>2.0): {(clean_z > 2.0).sum():,}")
    print(f"    Distress (<1.0): {(clean_z < 1.0).sum():,}")

    print(f"\n  Flagged data (1+ issues):")
    flagged_z = df[df["flag_data_quality_issues"] > 0]["AltmanZScore_Normalized"]
    print(f"    Mean: {flagged_z.mean():.2f}")
    print(f"    Median: {flagged_z.median():.2f}")
    print(f"    Safe (>2.0): {(flagged_z > 2.0).sum():,}")
    print(f"    Distress (<1.0): {(flagged_z < 1.0).sum():,}")

    # Examples of flagged records
    print(f"\n📋 EXAMPLES OF FLAGGED RECORDS:")

    print(f"\n  🔴 DATA ERROR: Negative Revenue (flag_x5_negative = 1):")
    x5_neg = df[df["flag_x5_negative"] > 0][["Symbol", "Date", "X5_SalesToTotalAssets", "X5_Normalized"]]
    if len(x5_neg) > 0:
        for idx, row in x5_neg.iterrows():
            print(f"     {row['Symbol']} {int(row['Date'])}: X5={row['X5_SalesToTotalAssets']:.6f} → {row['X5_Normalized']:.6f}")
    else:
        print(f"     None found")

    print(f"\n  🔴 INSOLVENT: TL > TA (flag_leverage_extreme = 1):")
    lev_extreme = df[df["flag_leverage_extreme"] > 0][["Symbol", "Date", "Leverage", "Leverage_Normalized"]].head(5)
    if len(lev_extreme) > 0:
        for idx, row in lev_extreme.iterrows():
            print(f"     {row['Symbol']} {int(row['Date'])}: Leverage={row['Leverage']:.2f} → {row['Leverage_Normalized']:.2f}")
    else:
        print(f"     None found")

    print(f"\n  ⚠️  Market Spike: X4 > Cap (flag_x4_spike = 1):")
    x4_spike = df[df["flag_x4_spike"] > 0][["Symbol", "Date", "X4_MarketValueToTotalLiabilities", "X4_Cap", "X4_Normalized"]].head(5)
    if len(x4_spike) > 0:
        for idx, row in x4_spike.iterrows():
            print(f"     {row['Symbol']} {int(row['Date'])}: X4={row['X4_MarketValueToTotalLiabilities']:.2f}x → Cap={row['X4_Cap']:.2f}x")
    else:
        print(f"     None found")

    print(f"\n  ⚠️  Extreme Loss: X2 < -0.5 (flag_x2_extreme = 1):")
    x2_ext = df[df["flag_x2_extreme"] > 0][["Symbol", "Date", "X2_RetainedEarningsToTotalAssets", "X2_Normalized"]].head(5)
    if len(x2_ext) > 0:
        for idx, row in x2_ext.iterrows():
            print(f"     {row['Symbol']} {int(row['Date'])}: X2={row['X2_RetainedEarningsToTotalAssets']:.4f} → {row['X2_Normalized']:.4f}")
    else:
        print(f"     None found")

    print("\n" + "=" * 120)


def focus_on_flag(df: pd.DataFrame, flag_name: str) -> None:
    """Detailed analysis of a specific flag."""

    if flag_name not in df.columns:
        print(f"❌ Flag '{flag_name}' not found in data")
        return

    flagged = df[df[flag_name] > 0]
    print(f"\n" + "=" * 120)
    print(f"DETAILED ANALYSIS: {flag_name}")
    print(f"=" * 120)

    print(f"\nTotal affected: {len(flagged):,} rows ({len(flagged)/len(df)*100:.1f}%)")

    # Show distribution by year
    print(f"\nDistribution by year:")
    year_dist = flagged["Date"].value_counts().sort_index()
    for year, count in year_dist.items():
        print(f"  {int(year)}: {count:,} rows")

    # Show distribution by company
    print(f"\nTop 10 companies affected:")
    company_dist = flagged["Symbol"].value_counts().head(10)
    for symbol, count in company_dist.items():
        print(f"  {symbol}: {count} occurrences")

    # Correlation with Z-score
    print(f"\nZ-Score statistics for flagged records:")
    flagged_z = flagged["AltmanZScore_Normalized"]
    print(f"  Mean: {flagged_z.mean():.2f}")
    print(f"  Median: {flagged_z.median():.2f}")
    print(f"  Min: {flagged_z.min():.2f}")
    print(f"  Max: {flagged_z.max():.2f}")

    # Show sample records
    print(f"\nFirst 10 flagged records:")
    cols = ["Symbol", "Date", "AltmanZScore_Normalized", "ROA", "Leverage"]
    display = flagged[cols].head(10)
    print(display.to_string(index=False))

    print("\n" + "=" * 120)


def export_by_flag(df: pd.DataFrame, output_path: Path, include_clean: bool = False) -> None:
    """Export flagged (or clean) records to CSV."""

    if include_clean:
        export_df = df[df["flag_data_quality_issues"] == 0]
        label = "CLEAN"
    else:
        export_df = df[df["flag_data_quality_issues"] > 0]
        label = "FLAGGED"

    output_path.parent.mkdir(parents=True, exist_ok=True)
    export_df.to_csv(output_path, index=False)

    print(f"✓ Exported {len(export_df):,} {label} records to {output_path}")
    print(f"  Columns: {len(export_df.columns)}")


def export_by_specific_flag(df: pd.DataFrame, output_path: Path, flag_name: str) -> None:
    """Export records matching a specific flag."""

    if flag_name not in df.columns:
        print(f"❌ Flag '{flag_name}' not found")
        return

    export_df = df[df[flag_name] > 0]
    output_path.parent.mkdir(parents=True, exist_ok=True)
    export_df.to_csv(output_path, index=False)

    print(f"✓ Exported {len(export_df):,} records with {flag_name} to {output_path}")


def main(argv: Optional[Sequence[str]] = None) -> None:
    parser = argparse.ArgumentParser(
        description="Analyze data quality flags from merged_filtered.csv"
    )
    parser.add_argument(
        "--data-dir", type=Path, default=Path.cwd(),
        help="Base data directory (default: cwd)"
    )
    parser.add_argument(
        "--report", action="store_true",
        help="Generate comprehensive flag analysis report"
    )
    parser.add_argument(
        "--focus", type=str,
        help="Focus on specific flag (e.g., flag_x4_spike)"
    )
    parser.add_argument(
        "--export-flagged", type=Path,
        help="Export flagged records to CSV"
    )
    parser.add_argument(
        "--export-clean", type=Path,
        help="Export clean records (no flags) to CSV"
    )
    parser.add_argument(
        "--export-flag", type=str,
        help="Export specific flag records to CSV (use with --output)"
    )
    parser.add_argument(
        "--output", type=Path,
        help="Output file for --export-flag"
    )

    args = parser.parse_args(argv)

    try:
        df = load_merged(args.data_dir)
    except FileNotFoundError as e:
        print(f"❌ Error: {e}")
        return

    # Default: show report if no other action specified
    if not any([args.report, args.focus, args.export_flagged, args.export_clean, args.export_flag]):
        args.report = True

    if args.report:
        analyze_all_flags(df)

    if args.focus:
        focus_on_flag(df, args.focus)

    if args.export_flagged:
        export_by_flag(df, args.export_flagged, include_clean=False)

    if args.export_clean:
        export_by_flag(df, args.export_clean, include_clean=True)

    if args.export_flag:
        if not args.output:
            print("❌ --export-flag requires --output <filename>")
            return
        export_by_specific_flag(df, args.output, args.export_flag)


if __name__ == "__main__":
    main()
